### ISSUE TITLE
Broken demo CodePen

### ISSUE THREAD

**Issue by veronQ** [AllThingsSmitty/responsive-css-grid#1]
Loaded CSS file returns an internal server error.  
https://codepen.io/AllThingsSmitty/pen/YqEbPB

**Comment by AllThingsSmitty** [comment]
Not sure how this slipped by me, but looking at it now, I'm see an internal server error with the demo on CodePen now. Could be the previous RawGit host, but I think this has been okay on gitcdn for a while.
